apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopverse-mysql-pvc
  namespace: shopverse
  labels:
    app: shopverse
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
