apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shopverse-storage
  labels:
    app: shopverse
provisioner: docker.io/hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
