apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopverse-backend-hpa
  namespace: shopverse
  labels:
    app: shopverse
    component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopverse-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    # Scale بناءً على CPU
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Scale Memory
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
