apiVersion: v1
kind: Service
metadata:
  name: shopverse-backend
  namespace: shopverse
  labels:
    app: shopverse
    component: backend
spec:
  selector:
    app: shopverse
    component: backend
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
