apiVersion: v1
kind: LimitRange
metadata:
  name: shopverse-limitrange
  namespace: shopverse
  labels:
    app: shopverse
spec:
  limits:
    # Container Limits
    - type: Container
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
    # Pod Limits
    - type: Pod
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
    # PVC Limits
    - type: PersistentVolumeClaim
      max:
        storage: "5Gi"
      min:
        storage: "1Gi"
