# Frontend Traefik
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shopverse-frontend-policy
  namespace: shopverse
  labels:
    app: shopverse
spec:
  podSelector:
    matchLabels:
      component: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Traefik namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
    # namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: shopverse
  egress:
    # Backend
    - to:
        - podSelector:
            matchLabels:
              component: backend
      ports:
        - port: 8080
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
# Backend and Frontend Traefik
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shopverse-backend-policy
  namespace: shopverse
  labels:
    app: shopverse
spec:
  podSelector:
    matchLabels:
      component: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Frontend
    - from:
        - podSelector:
            matchLabels:
              component: frontend
      ports:
        - port: 8080
    # Traefik
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - port: 8080
  egress:
    # MySQL
    - to:
        - podSelector:
            matchLabels:
              component: database
      ports:
        - port: 3306
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
# MySQL Backend InitContainer
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shopverse-database-policy
  namespace: shopverse
  labels:
    app: shopverse
spec:
  podSelector:
    matchLabels:
      component: database
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Backend
    - from:
        - podSelector:
            matchLabels:
              component: backend
      ports:
        - port: 3306
    - from:
        - podSelector:
            matchLabels:
              app: shopverse
      ports:
        - port: 3306
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
