apiVersion: v1
kind: ResourceQuota
metadata:
  name: shopverse-quota
  namespace: shopverse
  labels:
    app: shopverse
spec:
  hard:
    
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
    persistentvolumeclaims: "5"
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
