apiVersion: v1
kind: Secret
metadata:
  name: shopverse-secret
  namespace: shopverse
  labels:
    app: shopverse
type: Opaque
data:
  # القيم مشفرة بـ base64
  DB_PASSWORD: c2hvcHZlcnNlMTIz
  DB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  JWT_SECRET: c2hvcHZlcnNlLWp3dC1zZWNyZXQta2V5LTIwMjQ=
