# Role for Backend - reads secrets and configmaps 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shopverse-backend-role
  namespace: shopverse
  labels:
    app: shopverse
    component: backend
rules:
  # reads secrets (DB password, JWT secret)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  # reads configmaps (DB host, port, name)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  # reads pods (للـ health checks)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
# Role for Frontend -reads configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shopverse-frontend-role
  namespace: shopverse
  labels:
    app: shopverse
    component: frontend
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
