apiVersion: v1
kind: ResourceQuota
metadata:
  name: shopverse-quota
  namespace: {{ .Values.global.namespace }}
  labels:
    app: shopverse
spec:
  hard:
    pods: {{ .Values.resourceQuota.pods | quote }}
    services: {{ .Values.resourceQuota.services | quote }}
    secrets: {{ .Values.resourceQuota.secrets | quote }}
    configmaps: {{ .Values.resourceQuota.configmaps | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.pvcs | quote }}
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopverse-limitrange
  namespace: {{ .Values.global.namespace }}
  labels:
    app: shopverse
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
    - type: Pod
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
    - type: PersistentVolumeClaim
      max:
        storage: "5Gi"
      min:
        storage: "1Gi"
