apiVersion: v1
kind: Secret
metadata:
  name: shopverse-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: shopverse
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
